### ISSUE TITLE
Publish again "Evolution and dynamics of case fatality rate in the COVID19 pandemia" to get use of the new external links

### ISSUE THREAD

**Issue by vrivas** [JJ/covid-reports#14]
Hi @JJ ,
I've updated cfr-evolution.Rmd (see issue #13) so that external links can now be used when reading from RPubs (in fact, links in References still doesn't work, but I don't know to fix that error...in case it can be done).
Please, don't forget to republish the report at RPubs.

**Comment by JJ** [comment]
Thanks, @vrivas
